### ISSUE TITLE
circular import error 

### ISSUE THREAD

**Issue by ZareefJafar** [slimgroup/PyCurvelab#15]
when I am trying to 'import pyct' following error is showing:
Python 3.9.12, fftw-2.1.5, CurveLab-2.1.3 and swing 4.0.2

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zareef/software/PyCurvelab/pyct/__init__.py", line 23, in <module>
    from .fdct2 import fdct2
  File "/home/zareef/software/PyCurvelab/pyct/fdct2.py", line 9, in <module>
    from .fdct2_wrapper import *
  File "/home/zareef/software/PyCurvelab/pyct/fdct2_wrapper.py", line 13, in <module>
    from . import _fdct2_wrapper
ImportError: cannot import name '_fdct2_wrapper' from partially initialized module 'pyct' (most likely due to a circular import) (/home/zareef/software/PyCurvelab/pyct/__init__.py)
```

**Comment by cunhad** [comment]
I was able to fix this by using swig 3.0.12
